routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::middleware(['auth'])->group(function() {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('patients', 'PatientsController');
    Route::resource('patients.followups', 'FollowUpsController');
    Route::resource('members', 'MembersController');
    Route::resource('responsibles', 'ResponsiblesController');
    Route::resource('voluntaries', 'VoluntariesController');
    Route::resource('donations', 'DonationsController');

    Route::get('/reports/patients', 'ReportsController@patients')->name('reports.patients');
    Route::post('/reports/patients', 'ReportsController@patientsGenerate')->name('reports.patients.generate');

    Route::get('/reports/voluntaries', 'ReportsController@voluntaries')->name('reports.voluntaries');
    Route::post('/reports/voluntaries', 'ReportsController@voluntariesGenerate')->name('reports.voluntaries.generate');

    Route::get('/reports/donations', 'ReportsController@donations')->name('reports.donations');
    Route::post('/reports/donations', 'ReportsController@donationsGenerate')->name('reports.donations.generate');
});

app/Donation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Donation extends Model
{
    protected $fillable = [
        'descricao',
        'destino',
        'data_entrada',
        'vencimento',
        'data_saida'
    ];
    protected $dates = [
        'data_entrada',
        'vencimento',
        'data_saida'
    ];
    protected $casts = [
        'data_nascimento' => 'date:Y-m-d',
        'vencimento' => 'date:Y-m-d',
        'data_saida' => 'date:Y-m-d'
    ];

}

app/Http/Controllers/DonationsController.php
<?php

namespace App\Http\Controllers;

use App\Donation;
use Illuminate\Http\Request;

class DonationsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $donations = $this->search(Donation::query(), [
            'descricao' => request('q', null)
        ]);
        return view('donations.index', compact('donations'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('donations.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Donation $donation)
    {
        request()->validate([
            'donation.descricao' => 'required'
        ],
        [
            'donation.descricao.required' => 'O Campo Descrição é obrigatório.'
        ]);

        $createdDonation = $donation->create(request('donation'));

        return redirect()->route('donations.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Donation  $donation
     * @return \Illuminate\Http\Response
     */
    public function show(Donation $donation)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Donation  $donation
     * @return \Illuminate\Http\Response
     */
    public function edit(Donation $donation)
    {
        return view('donations.edit', compact('donation'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Donation  $donation
     * @return \Illuminate\Http\Response
     */
    public function update(Donation $donation, Request $request)
    {
        request()->validate([
            'donation.descricao' => 'required'
        ],
        [
            'donation.descricao.required' => 'O Campo Descrição é obrigatório.'
        ]);

        $donation->update(request('donation'));

        return redirect()->route('donations.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Donation  $donation
     * @return \Illuminate\Http\Response
     */
    public function destroy(Donation $donation)
    {
        $donation->delete();

        return redirect()->route('donations.index');
    }
}

resources/views/donations/create.blade.php
@extends('layouts.app')

@section('content')
<div class="card p-3">
  <div class="card-body">
    <h2 class="card-title">Cadastrar Doação</h2>
    <hr>
    <div class="row">
      <form action="{{route('donations.store')}}" method="POST">
        @csrf
        @include('shared.errors')
        <div class="row">
            @include('donations.forms.donation')
        </div>

        <div class="col-md-12 form-actions mt-4 d-flex justify-content-end">
          <button class="btn btn-primary">Salvar</button>
        </div>
      </form>
    </div>
  </div>
</div>
@endsection

resources/views/donations/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="card p-3">
  <div class="card-body">
    <h2 class="card-title">Editar Doação</h2>
    <hr>
    <div class="row">
      <form action="{{route('donations.update', $donation->id)}}" method="POST">
        @csrf
        @method('PUT')
        @include('shared.errors')
        <div class="row">
            @include('donations.forms.donation', ['donation' => $donation])
        </div>

        <div class="col-md-12 form-actions mt-4 d-flex justify-content-end">
          <button class="btn btn-primary">Salvar</button>
        </div>
      </form>
    </div>
  </div>
</div>
@endsection

resources/views/donations/index.blade.php
@extends('layouts.app')

@section('content')
@include('shared.search', [
    'placeholder' => 'Buscar pela descrição',
    'route' => 'donations.index',
    'text' => 'Cadastrar nova doação',
    'create' => 'donations.create',
])
<div class="row">
    <div class="col-md-12 card p-5">
        <table>
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Descrição</th>
                    <th>Destino</th>
                    <th>Entrada</th>
                    <th>Vencimento</th>
                    <th>Saida</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            @foreach($donations as $donation)
                <tr>
                    <td>{{$donation->id}}</td>
                    <td>{{$donation->descricao}}</td>
                    <td>{{$donation->destino}}</td>
                    <td>{{$donation->data_entrada->format('d/m/Y')}}</td>
                    <td>{{$donation->vencimento->format('d/m/Y')}}</td>
                    <td>{{$donation->data_saida->format('d/m/Y')}}</td>
                    <td>
                        <a href="{{route('donations.edit', $donation->id)}}">Editar</a>
                        @include('shared.delete', ['route' => 'donations', 'id' => $donation->id])
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>

        {{$donations->appends(['q' => request('q')])->links()}}
    </div>
</div>
@endsection