routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::middleware(['auth'])->group(function() {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('patients', 'PatientsController');
    Route::resource('patients.followups', 'FollowUpsController');
    Route::resource('members', 'MembersController');
    Route::resource('responsibles', 'ResponsiblesController');
    Route::resource('voluntaries', 'VoluntariesController');
    Route::resource('donations', 'DonationsController');

    Route::get('/reports/patients', 'ReportsController@patients')->name('reports.patients');
    Route::post('/reports/patients', 'ReportsController@patientsGenerate')->name('reports.patients.generate');

    Route::get('/reports/voluntaries', 'ReportsController@voluntaries')->name('reports.voluntaries');
    Route::post('/reports/voluntaries', 'ReportsController@voluntariesGenerate')->name('reports.voluntaries.generate');

    Route::get('/reports/donations', 'ReportsController@donations')->name('reports.donations');
    Route::post('/reports/donations', 'ReportsController@donationsGenerate')->name('reports.donations.generate');
});

app/Http/Controllers/FollowUpsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use \App\Patient;
use \App\PedagogyRecord;
use Illuminate\Support\Str;

class FollowUpsController extends Controller
{
    private $mappings = [
        'pedagogia' => 'pedagogyRecord',
        'fonoaudiologia' => 'phonoaudiologyRecord',
        'fisioterapia' => 'physiotherapyRecord',
        'assistente-social' => 'socialWorkerRecord',
        'psicologia' => 'psychologyRecord'
    ];

    public function create($id) {
        $patient = Patient::with(['responsible', $this->getRelationByRole() => function ($query) {
            $query->where('user_id', auth()->user()->id);
        }])->find($id);

        $idRecord = optional($patient->{$this->getRelationByRole()})->id;
        $relation = $patient->{$this->getRelationByRole()};

        return view('followups.new', compact('patient', 'idRecord', 'relation'));
    }

    public function store($id, Request $request) {
        $data = array_merge(request('followup'), ['patient_id' => $id]);
        $data['follow_ups'] = collect(request('follow_ups'))->reject(function ($item) {
            return is_null($item['date']) && is_null($item['text']);
        })->map(function ($item) {
            return array_merge($item, ['id' => Str::uuid()]);
        });

        auth()->user()->{$this->getRelationByRole()}()->create($data);

        return redirect()->back();
    }


    public function update($id, $idRecord, Request $request) {
        $user = auth()->user();

        $pedagogy = $user->{$this->getRelationByRole()}()->find($idRecord);

        $data = array_merge(request('followup'), ['patient_id' => $id]);
        $data['follow_ups'] = collect(request('follow_ups'))->reject(function ($item) {
            return is_null($item['date']) && is_null($item['text']);
        })->map(function ($item) {
            return array_merge($item, ['id' => Str::uuid()]);
        })->merge($pedagogy->follow_ups)->all();

       //dd($data);

        $pedagogy->update($data);

        return redirect()->back();
    }

    private function getRelationByRole() {
        $user = auth()->user();

        return $this->mappings[$user->role];
    }
}

resources/views/followups/new.blade.php
@extends('layouts.app')

@section('content')
<div class="card p-3">
  <div class="card-body">
    <h2 class="card-title">Adicionar FollowUp</h2>
    <hr>
    <form action="{{ $idRecord ? route('patients.followups.update', [$patient->id, $idRecord]) : route('patients.followups.store', $patient->id)}}" method="POST">
        @csrf
        @method($idRecord ? 'put' : 'post')

        @is('pedagogia')
            @include('followups.pedagogy', ['data' => $relation])
        @elseis('assistente-social')
            @include('followups.social_worker', ['data' => $relation])
        @else
            @include('followups.other', ['data' => $relation])
        @endis
        <h4>FollowUps</h4>
        <div class="form-group">
            <label for="date">Data</label>
            <input type="date" name="follow_ups[0][date]" class="form-control" />
        </div>
        <div class="form-group">
            <label for="date">Follow up</label>
            <textarea name="follow_ups[0][text]" class="form-control" id="" cols="30" rows="3"></textarea>
        </div>

        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Data</th>
                    <th>FollowUp</th>
                </tr>
            </thead>
            <tbody>
                @if($relation)
                    @foreach($relation->follow_ups as $followUp)
                    <tr>
                        <td>{{$followUp->date}}</td>
                        <td>{{$followUp->text}}</td>
                    </tr>
                    @endforeach
                @endif
            </tbody>
        </table>

        <div class="col-md-12 form-actions mt-4 d-flex justify-content-end">
          <button class="btn btn-primary">Salvar</button>
        </div>
      </form>
  </div>
</div>
@endsection

resources/views/followups/other.blade.php
<table class="table table-bordered">
  <tr>
    <td>Nome do atendido</td>
    <td>{{$patient->nome}}</td>
  </tr>
  <tr>
    <td>Data de nascimento</td>
    <td>{{$patient->data_nascimento->format('d/m/Y')}}</td>
  </tr>
  <tr>
    <td>Deficiência</td>
    <td>{{$patient->deficiencia}}</td>
  </tr>
  <tr>
    <td>Prognóstico</td>
    <td><input type="text" name="followup[prognostico]" class="form-control" value="{{optional($data)->prognostico}}"/></td>
  </tr>
  <tr>
    <td>Diagnóstico</td>
    <td><input type="text" name="followup[diagnostico]" class="form-control" value="{{optional($data)->diagnostico}}"/></td>
  </tr>
  <tr>
    <td>Plano de tratamento</td>
    <td><input type="text" name="followup[plano_tratamento]" class="form-control" value="{{optional($data)->plano_tratamento}}"/></td>
  </tr>
</table>

resources/views/followups/pedagogy.blade.php
<table class="table table-bordered">
          <tr>
            <td>Nome do atendido</td>
            <td>{{$patient->nome}}</td>
          </tr>
          <tr>
            <td>Data de nascimento</td>
            <td>{{$patient->data_nascimento->format('d/m/Y')}}</td>
          </tr>
          <tr>
            <td>Deficiência</td>
            <td>{{$patient->deficiencia}}</td>
          </tr>
          <tr>
            <td>Etilogia</td>
            <td>{{$patient->etilogia}}</td>
          </tr>
          <tr>
            <td>Responsável</td>
            <td>{{optional($patient->responsible)->nome}}</td>
          </tr>
          <tr>
            <td>Alteração Sensorial</td>
            <td><input type="text" name="followup[alteracao_sensorial]" class="form-control" value="{{optional($patient->pedagogyRecord)->alteracao_sensorial}}"/></td>
          </tr>
          <tr>
            <td>Alteração Comportamental</td>
            <td><input type="text" name="followup[alteracao_comportamental]" class="form-control" value="{{optional($patient->pedagogyRecord)->alteracao_comportamental}}"/></td>
          </tr>
          <tr>
            <td>Medicação</td>
            <td>{{$patient->mediacao}}</td>
          </tr>
          <tr>
            <td>Escola</td>
            <td><input type="text" name="followup[escola]" class="form-control" value="{{optional($patient->pedagogyRecord)->escola}}"/></td>
          </tr>
        </table>

resources/views/followups/social_worker.blade.php
<table class="table table-bordered">
  <tr>
    <td>Nome do atendido</td>
    <td>{{$patient->nome}}</td>
  </tr>
  <tr>
    <td>Renda Familiar</td>
    <td><input type="number" name="followup[renda_familia]" class="form-control" value="{{optional($data)->renda_familia}}"/></td>
  </tr>
  <tr>
    <td>Renda Per Capita</td>
    <td><input type="text" name="followup[renda_percapita]" class="form-control" value="{{optional($data)->renda_percapita}}"/></td>
  </tr>
  <tr>
    <td>Beneficios</td>
    <td><input type="text" name="followup[beneficios]" class="form-control" value="{{optional($data)->beneficios}}"/></td>
  </tr>
  <tr>
    <td>Condições de moradia</td>
    <td><input type="text" name="followup[condicao_moradia]" class="form-control" value="{{optional($data)->condicao_moradia}}"/></td>
  </tr>
</table>