routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::middleware(['auth'])->group(function() {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('patients', 'PatientsController');
    Route::resource('patients.followups', 'FollowUpsController');
    Route::resource('members', 'MembersController');
    Route::resource('responsibles', 'ResponsiblesController');
    Route::resource('voluntaries', 'VoluntariesController');
    Route::resource('donations', 'DonationsController');

    Route::get('/reports/patients', 'ReportsController@patients')->name('reports.patients');
    Route::post('/reports/patients', 'ReportsController@patientsGenerate')->name('reports.patients.generate');

    Route::get('/reports/voluntaries', 'ReportsController@voluntaries')->name('reports.voluntaries');
    Route::post('/reports/voluntaries', 'ReportsController@voluntariesGenerate')->name('reports.voluntaries.generate');

    Route::get('/reports/donations', 'ReportsController@donations')->name('reports.donations');
    Route::post('/reports/donations', 'ReportsController@donationsGenerate')->name('reports.donations.generate');
});

app/Voluntary.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Voluntary extends Model
{
    protected $fillable = [
        'nome',
        'data_nascimento',
        'conjuge',
        'estado_civil',
        'filhos',
        'telefone',
        'celular',
        'companhia',
        'funcao',
        'data_reuniao',
        'quando_comeca',
        'horario_disponiveis'
    ];
    protected $dates = ['data_nascimento'];

    protected $casts = [
        'data_nascimento' => 'date:Y-m-d',
        'data_reuniao' => 'date:Y-m-d'
    ];

    public function address() {
        return $this->morphOne('App\Address', 'addressable');
    }

    public function document() {
        return $this->morphOne('App\Document', 'documentable');
    }

    public function getDataReuniaoAttribute() {
        return $this->attributes['data_reuniao'];
    }
}

app/Http/Controllers/VoluntariesController.php
<?php

namespace App\Http\Controllers;

use App\Voluntary;
use Illuminate\Http\Request;

class VoluntariesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $voluntaries = $this->search(Voluntary::query(), [
            'nome' => request('q', null),
        ]);

        return view('voluntaries.index', compact('voluntaries'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('voluntaries.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Voluntary $voluntary)
    {
       request()->validate([
            'voluntary.nome' => 'required',
            'voluntary.data_nascimento' => 'required',
            'voluntary.conjuge' => 'required',
            'voluntary.telefone' => 'required',
            'document.identidade_numero' => 'required',
            'document.identidade_uf' => 'required',
            'document.cpf' => 'required|cpf',
            'address.cep' => 'required',
            'address.rua' => 'required',
            'address.numero' => 'required',
            'address.bairro' => 'required',
            'address.cidade' => 'required',
            'address.estado' => 'required',
        ],
        [
            'voluntary.nome.required' => 'O Campo Nome é obrigatório.',
            'voluntary.data_nascimento.required' => 'O Campo Data de nascimento é obrigatório.',
            'voluntary.conjuge.required' => 'O Campo Conjuge é obrigatório.',
            'voluntary.telefone.required' => 'O Campo Telefone é obrigatório.',
            'document.identidade_numero.required' => 'O Campo Telefone é obrigatório.',
            'document.identidade_uf.required' => 'O Campo Deficiência é obrigatório.',
            'address.cep.required' => 'O Campo Cep é obrigatório.',
            'address.rua.required' => 'O Campo Rua é obrigatório.',
            'address.numero.required' => 'O Campo Número é obrigatório.',
            'address.bairro.required' => 'O Campo bairro é obrigatório.',
            'address.cidade.required' => 'O Campo Cidade é obrigatório.',
            'address.estado.required' => 'O Campo Bairro é obrigatório.',
            'document.cpf.required' => 'O Campo Cpf é obrigatório.',
            'document.cpf.cpf' => 'O Campo Cpf não é um cpf válido.'
        ]);

        $createdVoluntary = $voluntary->create(request('voluntary'));

        $createdVoluntary->address()->save(new \App\Address(request('address')));
        $createdVoluntary->document()->create(request('document'));

        return redirect()->route('voluntaries.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Voluntary  $voluntary
     * @return \Illuminate\Http\Response
     */
    public function show(Voluntary $voluntary)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Voluntary  $voluntary
     * @return \Illuminate\Http\Response
     */
    public function edit(Voluntary $voluntary)
    {
        return view('voluntaries.edit', compact('voluntary'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Voluntary  $voluntary
     * @return \Illuminate\Http\Response
     */
    public function update(Voluntary $voluntary, Request $request)
    {
       request()->validate([
            'voluntary.nome' => 'required',
            'voluntary.data_nascimento' => 'required',
            'voluntary.conjuge' => 'required',
            'voluntary.telefone' => 'required',
            'document.identidade_numero' => 'required',
            'document.identidade_uf' => 'required',
            'document.cpf' => 'required|cpf',
            'address.cep' => 'required',
            'address.rua' => 'required',
            'address.numero' => 'required',
            'address.bairro' => 'required',
            'address.cidade' => 'required',
            'address.estado' => 'required',
        ],
        [
            'voluntary.nome.required' => 'O Campo Nome é obrigatório.',
            'voluntary.data_nascimento.required' => 'O Campo Data de nascimento é obrigatório.',
            'voluntary.conjuge.required' => 'O Campo Conjuge é obrigatório.',
            'voluntary.telefone.required' => 'O Campo Telefone é obrigatório.',
            'document.identidade_numero.required' => 'O Campo Telefone é obrigatório.',
            'document.identidade_uf.required' => 'O Campo Deficiência é obrigatório.',
            'address.cep.required' => 'O Campo Cep é obrigatório.',
            'address.rua.required' => 'O Campo Rua é obrigatório.',
            'address.numero.required' => 'O Campo Número é obrigatório.',
            'address.bairro.required' => 'O Campo bairro é obrigatório.',
            'address.cidade.required' => 'O Campo Cidade é obrigatório.',
            'address.estado.required' => 'O Campo Bairro é obrigatório.',
            'document.cpf.required' => 'O Campo Cpf é obrigatório.',
            'document.cpf.cpf' => 'O Campo Cpf não é um cpf válido.'
        ]);

        $voluntary->update(request('voluntary'));

        $voluntary->address()->update(request('address'));
        $voluntary->document()->update(request('document'));

        return redirect()->route('voluntaries.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Voluntary  $voluntary
     * @return \Illuminate\Http\Response
     */
    public function destroy(Voluntary $voluntary)
    {
        $voluntary->delete();

        return redirect()->route('voluntaries.index');
    }
}

resources/views/voluntaries/create.blade.php
@extends('layouts.app')

@section('content')
<div class="card p-3">
  <div class="card-body">
    <h2 class="card-title">Cadastrar Voluntário</h2>
    <hr>
    <div class="row">
      <form action="{{route('voluntaries.store')}}" method="POST">
        @csrf
        @include('shared.errors')
        <div class="col-md-2 mt-4">
          <h3>Dados Pessoais</h3>
        </div>
        <div class="col-md-10 mt-4">
          <div class="row">
            @include('voluntaries.forms.voluntary')
          </div>
        </div>

        <div class="col-md-2 mt-4">
          <h3>Endereço</h3>
        </div>
        <div class="col-md-10 mt-4">
          <div class="row">
            @include('shared.address')
          </div>
        </div>

        <div class="col-md-2 mt-4">
          <h3>Documentos</h3>
        </div>
        <div class="col-md-10 mt-4">
          <div class="row">
            @include('shared.documents')
          </div>
        </div>

        <div class="col-md-12 form-actions mt-4 d-flex justify-content-end">
          <button class="btn btn-primary">Salvar</button>
        </div>
      </form>
    </div>
  </div>
</div>
@endsection

resources/views/voluntaries/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="card p-3">
  <div class="card-body">
    <h2 class="card-title">Editar Responsavel</h2>
    <hr>
    <div class="row">
      <form action="{{route('voluntaries.update', $voluntary->id)}}" method="POST">
        @csrf
        @method('PUT')
        @include('shared.errors')
        <div class="col-md-2 mt-4">
          <h3>Dados Pessoais</h3>
        </div>
        <div class="col-md-10 mt-4">
          <div class="row">
            @include('voluntaries.forms.voluntary', ['voluntary' => $voluntary])
          </div>
        </div>

        <div class="col-md-2 mt-4">
          <h3>Endereço</h3>
        </div>
        <div class="col-md-10 mt-4">
          <div class="row">
            @include('shared.address', ['data' => $voluntary->address])
          </div>
        </div>

        <div class="col-md-2 mt-4">
          <h3>Documentos</h3>
        </div>
        <div class="col-md-10 mt-4">
          <div class="row">
            @include('shared.documents', ['data' => $voluntary->document])
          </div>
        </div>

        <div class="col-md-12 form-actions mt-4 d-flex justify-content-end">
          <button class="btn btn-primary">Salvar</button>
        </div>
      </form>
    </div>
  </div>
</div>
@endsection

resources/views/voluntaries/index.blade.php
@extends('layouts.app')

@section('content')
@include('shared.search', [
    'placeholder' => 'Buscar pelo nome',
    'route' => 'voluntaries.index',
    'create' => 'voluntaries.create',
    'text' => 'Cadastrar novo voluntário'
])
<div class="row">
    <div class="col-md-12 card p-5">
        <table>
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Nome</th>
                    <th>Data de nascimento</th>
                    <th>Função</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            @foreach($voluntaries as $voluntary)
                <tr>
                    <td>{{$voluntary->id}}</td>
                    <td>{{$voluntary->nome}}</td>
                    <td>{{$voluntary->data_nascimento->format('d/m/Y')}}</td>
                    <td>{{$voluntary->funcao}}</td>
                    <td>
                        <a href="{{route('voluntaries.edit', $voluntary->id)}}">Editar</a>
                        @include('shared.delete', ['route' => 'voluntaries', 'id' => $voluntary->id])
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>

        {{$voluntaries->links()}}
    </div>
</div>
@endsection