routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::middleware(['auth'])->group(function() {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('patients', 'PatientsController');
    Route::resource('patients.followups', 'FollowUpsController');
    Route::resource('members', 'MembersController');
    Route::resource('responsibles', 'ResponsiblesController');
    Route::resource('voluntaries', 'VoluntariesController');
    Route::resource('donations', 'DonationsController');

    Route::get('/reports/patients', 'ReportsController@patients')->name('reports.patients');
    Route::post('/reports/patients', 'ReportsController@patientsGenerate')->name('reports.patients.generate');

    Route::get('/reports/voluntaries', 'ReportsController@voluntaries')->name('reports.voluntaries');
    Route::post('/reports/voluntaries', 'ReportsController@voluntariesGenerate')->name('reports.voluntaries.generate');

    Route::get('/reports/donations', 'ReportsController@donations')->name('reports.donations');
    Route::post('/reports/donations', 'ReportsController@donationsGenerate')->name('reports.donations.generate');
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- CSRF Token -->
  <meta name="csrf-token" content="{{ csrf_token() }}">

  <title>{{ config('app.name', 'Instituto Bruno') }}</title>

  <!-- Scripts -->
  <script src="{{ asset('js/app.js') }}" defer></script>

  <!-- Fonts -->
  <link rel="dns-prefetch" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

  <!-- Styles -->
  <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
  <div id="app">
    <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
      <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
          {{ config('app.name', 'Instituto Bruno') }}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <!-- Left Side Of Navbar -->
          <ul class="navbar-nav mr-auto">
            @auth
            @is('secretaria')
              <div class="dropdown">
                <button class="btn btn-link dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Modulos
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  <a class="dropdown-item" href="{{route('patients.index')}}">Pacientes</a>
                  <a class="dropdown-item" href="{{route('members.index')}}">Membros</a>
                  <a class="dropdown-item" href="{{route('responsibles.index')}}">Responsáveis</a>
                  <a class="dropdown-item" href="{{route('voluntaries.index')}}">Voluntários</a>
                  <a class="dropdown-item" href="{{route('donations.index')}}">Doação</a>
                </div>
              </div>
              <div class="dropdown">
                <button class="btn btn-link dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Relatório
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  <a class="dropdown-item" href="{{route('reports.patients')}}">Paciente</a>
                  <a class="dropdown-item" href="{{route('reports.voluntaries')}}">Voluntário</a>
                  <a class="dropdown-item" href="{{route('reports.donations')}}">Doações</a>
                </div>
              </div>
            @else
                <div class="dropdown">
                    <button class="btn btn-link dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Modulos
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                      <a class="dropdown-item" href="{{route('patients.index')}}">Pacientes</a>
                    </div>
                  </div>
            @endis
            @endauth
          </ul>

          <!-- Right Side Of Navbar -->
          <ul class="navbar-nav ml-auto">
            <!-- Authentication Links -->
            @guest
            <li class="nav-item">
              <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
            </li>
            @else
            <li class="nav-item dropdown">
              <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                {{ Auth::user()->name }} <span class="caret"></span>
              </a>

              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{{ route('logout') }}"
                onclick="event.preventDefault();
                document.getElementById('logout-form').submit();">
                Sair
              </a>

              <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
              </form>
            </div>
          </li>
          @endguest
        </ul>
      </div>
    </div>
  </nav>

  <main class="py-4 container">
    @yield('content')
  </main>
</div>
</body>
</html>